

GET https://jsonplaceholder.typicode.com/

### ユーザー一覧

PUT https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
    "id": "1",
    "title": "foo",
    "body": "bar",
    "userId": 1
}

